version: '2.1'

services:
  everydocs_core:
    image: jonashellmann/everydocs:latest
    restart: unless-stopped
    depends_on:
      everydocs_db:
        condition: service_healthy
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - EVERYDOCS_DB_ADAPTER=mysql2
      - EVERYDOCS_DB_NAME=everydocs
      - EVERYDOCS_DB_USER=everydocs
      - EVERYDOCS_DB_PASSWORD=PASSWORD123!
      - EVERYDOCS_DB_HOST=everydocs_db
      - EVERYDOCS_DB_PORT=3306
    volumes:
      - /data/everydocs:/var/everydocs-files
    ports:
      - '5678:5678'

  everydocs_web:
    image: jonashellmann/everydocs-web:latest
    restart: unless-stopped
    volumes:
      - ./everydocs-web-config.js:/usr/local/apache2/htdocs/config.js
    ports:
      - '8080:80'
      - '8443:443'

  everydocs_db:
    image: mariadb:10.7.3
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=everydocs
      - MYSQL_USER=everydocs
      - MYSQL_PASSWORD=PASSWORD123!
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h everydocs_db -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
    db_data: